name: CI Docker - Jurassic Park

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Launch the docker container
      run: |
        docker compose build
        docker compose up
