name: CI Jurassic Park

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Compose
      run: docker-compose up --build

    - name: Wait for MySQL to be healthy
      run: |
        echo "⏳ Waiting for mysql1 and mysql2 to be healthy..."
        docker-compose ps
        docker-compose exec mysql1 sh -c "until mysqladmin ping -h localhost -u root -ppassword --silent; do sleep 2; done"
        docker-compose exec mysql2 sh -c "until mysqladmin ping -h localhost -u root -ppassword --silent; do sleep 2; done"

    - name: Run tests via make
      run: |
        make up
        make test-api1
        make test-api2
        make down

    # - name: Run tests on API 1
    #   run: docker-compose exec api1 npm test

    # - name: Run tests on API 2
    #   run: docker-compose exec api2 npm test

    - name: Tear down
      if: always()
      run: docker-compose down
